### PR TITLE
Matts updates

### PR DESCRIPTION
**Pull request by mattyeag**

### CODE REVIEW

**Comment by mourkeer** [comment]
"matt's updates"? How about describing what you did :P

**Comment by mattyeag** [comment]
Hey now! ha. I did to many different things. I tried to describe it in the comments section better.

**Comment by mourkeer** [comment]
The commit history on this branch is incorrect. You have rohan's commit as well as mine since you merged our branches into yours. That's fine, I had to do that too. However, you need to remove changes that don't belong to the branch when you do a pull request.
run the following on your "matt's updates" branch.
```bash
git rebase -i HEAD~12
```

This will open up vim with the list of commits. You just need to delete the lines that correspond to commits you didn't write: "Added initial swipe navigation..." and "gameplay view can now populate level data".

Save the file and quit vim. That will cause git to rewrite history without the commits that don't belong to you. This is important because those two commits that belong to me and rohan are already in their own PR's, so we don't want them in yours as well.

After doing this, you should **rebase** (don't merge) with master again since my PR is merged and Rohan's is about to be. That will properly implement the commits in the correct order.

**Comment by mattyeag** [comment]
oh OK. I can do that. Yea I remember you wanting us to use rebase but we stopped using the master branch so wasn't sure how to implement. will do it soon.

**Pull request closed without merging**
